sudo: false
language: node_js
node_js:
  - '12'
  - '10'
  - '8'
install:
  - npm install -g grunt-cli
  - npm install
  - npm run test
after_script:
  - npm run coveralls
notifications:
  email:
    on_success: never
